## Mini Exercise 2 – Feature Engineering

Imports

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

1. The file mini_data.csv contains 3 features (X, Y and Z) and the table below shows our entire
dataset.

In [3]:
# Load csv file
mini_data = pd.read_csv('mini_data.csv')
print(mini_data)

     X    Y    Z
0  1.3  1.0  1.2
1  3.5  3.4  3.3
2  3.2  2.9  3.1
3  1.1  0.9  1.1
4  1.4  1.2  1.1
5  0.9  0.8  0.9
6  4.2  3.9  4.1
7  3.8  3.9  4.2
8  1.2  1.0  1.0
9  3.7  3.5  3.7


2. The dataset has not been standardized.
3. Write Python code to perform standardization on the data, and show that your standardized data (i.e. each of your non-categorical features) has zero-mean and unit-variance. Feel free to use any NumPy functions, such as numpy.mean() and numpy.std(), in your solution.

In [22]:
# 1. Use StandardScaler to zero-mean
scaler = StandardScaler()
mini_data_scaled = scaler.fit_transform(mini_data)
print(f"After standardisation:\n{mini_data_scaled}")

# 2. Show that mean = zero (zero-mean)
# Round to show zero-values (if mean is close to zero)
mean = np.mean(mini_data_scaled, axis = 0).round()
print(f"\nMean: {mean}")

# 3. Show that SD (variance**2) = 1, meaning variance = 1 (unit-variance)
sd = np.std(mini_data_scaled, axis = 0)
print(f"\nStandard deviation: {sd}")

After standardisation:
[[-0.88451471 -0.96139625 -0.86867085]
 [ 0.83754933  0.88448455  0.69048196]
 [ 0.60272241  0.49992605  0.54199122]
 [-1.04106599 -1.03830795 -0.94291623]
 [-0.80623907 -0.80757285 -0.94291623]
 [-1.19761727 -1.11521965 -1.09140697]
 [ 1.3854788   1.26904305  1.28444494]
 [ 1.07237624  1.26904305  1.35869031]
 [-0.96279035 -0.96139625 -1.0171616 ]
 [ 0.99410061  0.96139625  0.98746345]]

Mean: [-0. -0. -0.]

Standard deviation: [1. 1. 1.]


4. Find out what happens if we perform standardization on a dataset that has already been
standardized? Explain the outcome.

In [26]:
# 1. Retry standardisation on standardised data
mini_data_scaled2 = scaler.fit_transform(mini_data_scaled)
print(f"After restandardisation:\n{mini_data_scaled2}")

# Values are the same because the data is already standardised to mean = 0, sd = 1

After restandardisation:
[[-0.88451471 -0.96139625 -0.86867085]
 [ 0.83754933  0.88448455  0.69048196]
 [ 0.60272241  0.49992605  0.54199122]
 [-1.04106599 -1.03830795 -0.94291623]
 [-0.80623907 -0.80757285 -0.94291623]
 [-1.19761727 -1.11521965 -1.09140697]
 [ 1.3854788   1.26904305  1.28444494]
 [ 1.07237624  1.26904305  1.35869031]
 [-0.96279035 -0.96139625 -1.0171616 ]
 [ 0.99410061  0.96139625  0.98746345]]
