# NumPy

NumPy (Numerical Python) is the foundation of the entire Python scientific computing stack. It provides fast, memory-efficient multi-dimensional arrays and vectorised operations — making it 10–100x faster than plain Python lists for numerical work.

> Every ML library uses NumPy arrays under the hood. Mastering NumPy is essential before learning Pandas, Scikit-learn, or deep learning.

## Why NumPy?

NumPy provides fast, memory-efficient multi-dimensional arrays and vectorised operations.

In [1]:
import numpy as np

# Speed comparison: sum 1 million numbers
import time

# Python list
py_list = list(range(1_000_000))
start = time.time()
total = sum(py_list)
py_time = time.time() - start

# NumPy array
np_arr = np.arange(1_000_000)
start = time.time()
total = np.sum(np_arr)
np_time = time.time() - start

print(f"Python list: {py_time*1000:.1f} ms")
print(f"NumPy array: {np_time*1000:.1f} ms")
print(f"NumPy is {py_time/np_time:.0f}x faster!")

# Memory comparison
import sys
print(f"\nPython list size: {sys.getsizeof(py_list)/1024:.0f} KB")
print(f"NumPy array size: {np_arr.nbytes/1024:.0f} KB")

Python list: 8.7 ms
NumPy array: 2.2 ms
NumPy is 4x faster!

Python list size: 7813 KB
NumPy array size: 7812 KB


## Creating NumPy Arrays

The core object is the `ndarray` (N-dimensional array). You can create arrays from Python lists/tuples using `np.array()`, or use built-in constructors:

- `np.array([1,2,3])` — from list or tuple
- `np.zeros((2,3))` — all zeros
- `np.ones((3,3))` — all ones
- `np.arange(0,10,2)` — like `range()`, returns array
- `np.linspace(0,1,5)` — evenly spaced floats
- `np.eye(3)` — 3×3 identity matrix
- `np.full((2,3), 7)` — fill with a value

> `np.linspace` is especially useful in ML for generating evenly spaced values for plotting decision boundaries or learning rate schedules.

In [2]:
import numpy as np

# From list
a = np.array([1, 2, 3])
print("From list:", a)

# From tuple
b = np.array((4, 5, 6))
print("From tuple:", b)

# 2D array (matrix)
mat = np.array([[1, 2, 3], [4, 5, 6]])
print(f"\n2D array:\n{mat}")
print(f"Type: {type(mat)}")

# Built-in constructors
print(f"\nzeros(2,3):\n{np.zeros((2,3))}")
print(f"\nones(3):\n{np.ones(3)}")
print(f"\narange(0,10,2): {np.arange(0,10,2)}")
print(f"\nlinspace(0,1,5): {np.linspace(0,1,5)}")
print(f"\neye(3):\n{np.eye(3)}")

From list: [1 2 3]
From tuple: [4 5 6]

2D array:
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>

zeros(2,3):
[[0. 0. 0.]
 [0. 0. 0.]]

ones(3):
[1. 1. 1.]

arange(0,10,2): [0 2 4 6 8]

linspace(0,1,5): [0.   0.25 0.5  0.75 1.  ]

eye(3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Dimensions, Shape & dtype

Every array has:
- `.ndim` — number of axes (0D=scalar, 1D=vector, 2D=matrix)
- `.shape` — tuple of sizes, e.g. `(3,4)` = 3 rows × 4 cols
- `.size` — total element count
- `.dtype` — data type (`int64`, `float64`, `bool`, etc.)

> Shape errors are the #1 debugging headache in ML. Always check `.shape` when things go wrong! A `(3,)` array and a `(3,1)` array behave very differently.

In [3]:
import numpy as np

# 0D (scalar)
s = np.array(42)
print(f"0D: value={s}, ndim={s.ndim}, shape={s.shape}")

# 1D (vector)
v = np.array([1, 2, 3, 4, 5])
print(f"1D: ndim={v.ndim}, shape={v.shape}, size={v.size}")

# 2D (matrix) — 2 rows × 3 columns
m = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D: ndim={m.ndim}, shape={m.shape}, size={m.size}")

# 3D — 2 "layers" of 2×3 matrices
t = np.array([[[1,2,3],[4,5,6]],
              [[7,8,9],[10,11,12]]])
print(f"3D: ndim={t.ndim}, shape={t.shape}")

# dtype — data type
print(f"\nint array dtype: {v.dtype}")
f = np.array([1.0, 2.5, 3.7])
print(f"float array dtype: {f.dtype}")

# Force a specific dtype
x = np.array([1, 2, 3], dtype=np.float32)
print(f"Forced float32: {x}, dtype={x.dtype}")

0D: value=42, ndim=0, shape=()
1D: ndim=1, shape=(5,), size=5
2D: ndim=2, shape=(2, 3), size=6
3D: ndim=3, shape=(2, 2, 3)

int array dtype: int64
float array dtype: float64
Forced float32: [1. 2. 3.], dtype=float32


## Reshaping Arrays

Reshaping changes the shape without changing the data. The total number of elements must stay the same.

- `arr.reshape(rows, cols)` — new shape, same data
- `reshape(-1, 3)` — auto-calculate rows
- `reshape(4, -1)` — auto-calculate cols
- `arr.flatten()` — always returns 1D copy
- `arr.ravel()` — 1D view (no copy, faster)
- `arr.T` — transpose (swap rows ↔ cols)

> In ML, you constantly reshape data: flattening images to vectors, reshaping model inputs, transposing weight matrices. The `-1` trick is used everywhere.

In [4]:
import numpy as np

arr = np.arange(1, 13)  # [1, 2, ..., 12]
print(f"Original: {arr}, shape={arr.shape}")

# Reshape to 4×3
m = arr.reshape(4, 3)
print(f"\nReshaped (4,3):\n{m}")

# Reshape to 2×6 using -1
m2 = arr.reshape(2, -1)  # -1 = auto
print(f"\nReshaped (2,-1):\n{m2}")

# Reshape to 3D: 2 layers × 2 rows × 3 cols
m3 = arr.reshape(2, 2, 3)
print(f"\n3D shape: {m3.shape}")

# Flatten back to 1D
flat = m.flatten()
print(f"\nFlattened: {flat}")

# Transpose
print(f"\nTranspose of (4,3):\n{m.T}")
print(f"Transpose shape: {m.T.shape}")

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12], shape=(12,)

Reshaped (4,3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Reshaped (2,-1):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

3D shape: (2, 2, 3)

Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Transpose of (4,3):
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Transpose shape: (3, 4)


---
### Part 1 Exercises — Creating Arrays, Dimensions, Shape & dtype

Work through each exercise in the code cell below it.  
Try to solve without looking back at the examples first.

**Exercise 1.1 — Array properties**

Create a NumPy array from the list `[3, 6, 9, 12, 15]`.  
Print its `ndim`, `shape`, `size`, and `dtype`.  
Then recreate it with `dtype=float32` and confirm the dtype changed.

In [ ]:
# Exercise 1.1
import numpy as np

# Create the array

# Print ndim, shape, size, dtype

# Recreate as float32 and confirm dtype

**Exercise 1.2 — Built-in constructors**

Using only NumPy constructors (no `np.array([...])`):  
(a) Create a **3×5** matrix of zeros.  
(b) Create a 1D array of **8 ones** with dtype `float32`.  
(c) Create a **4×4** matrix where every element equals `9`.  
(d) Create a **5×5** identity matrix.

In [ ]:
# Exercise 1.2
import numpy as np

# (a) 3x5 zeros

# (b) 8 ones, float32

# (c) 4x4 filled with 9

# (d) 5x5 identity

**Exercise 1.3 — `arange` vs `linspace`**

(a) Use `np.arange` to produce `[0, 2, 4, 6, 8, 10]`.  
(b) Use `np.linspace` to produce exactly **6** evenly-spaced values from 0 to 10 inclusive.  
(c) Print both arrays and explain the key difference in a comment.

In [ ]:
# Exercise 1.3
import numpy as np

# (a) arange — specifies the STEP

# (b) linspace — specifies the COUNT

# (c) print and compare
# Key difference: ...

**Exercise 1.4 — dtype and type conversion**

Given `arr = np.array([1, 2, 3, 4])`:  
(a) Print its default `dtype`.  
(b) Create `arr_f` — the same values as `float64`.  
(c) Create `arr_bool` — a boolean array that is `True` where `arr > 2`.  
(d) Try `np.array([1, 2, 3.0, 4])`. What dtype does NumPy choose and why?

In [ ]:
# Exercise 1.4
import numpy as np
arr = np.array([1, 2, 3, 4])

# (a)

# (b)

# (c)

# (d)  # NumPy upcasts to float64 because...

**Exercise 1.5 — ML context: Feature matrix initialisation**

In ML a dataset is a 2D array of shape `(n_samples, n_features)`.  

(a) Create a placeholder feature matrix: **150 samples × 4 features**, initialised to zeros.  
(b) Print its `shape`, `ndim`, and total `size`.  
(c) Create a label vector of **150 zeros** as dtype `int32` (class labels 0/1).  
(d) What is the shape of the label vector? Why `(150,)` and not `(150, 1)`?

In [ ]:
# Exercise 1.5
import numpy as np

# (a)

# (b)

# (c)

# (d) # Shape is (150,) because...

**Exercise 1.6 — Reshaping and the `-1` trick**

(a) Create `arr = np.arange(1, 25)` (integers 1–24).  
(b) Reshape to `(4, 6)`. Print the result.  
(c) Reshape to `(2, 3, 4)`. Print only the shape.  
(d) Use `reshape(-1, 8)` — let NumPy infer the rows. How many rows does it give?  
(e) Flatten the `(2, 3, 4)` array back to 1D with `.flatten()`.

In [ ]:
# Exercise 1.6
import numpy as np

# (a)

# (b)

# (c)

# (d)

# (e)

## Indexing & Slicing

NumPy uses 0-based indexing. For multi-dimensional arrays, use comma-separated indices: `arr[row, col]`. Slicing uses `[start:stop:step]` syntax per dimension.

- `arr[0]` — first element (1D) or first row (2D)
- `arr[1, 2]` — row 1, col 2 in a 2D array
- `arr[-1]` — last element/row
- `arr[0:3]` — first 3 elements
- `arr[:, 0]` — entire first column
- `arr[0:2, 1:3]` — sub-matrix

> The comma syntax `arr[row, col]` is unique to NumPy — Python lists require `arr[row][col]`. NumPy's syntax is cleaner and faster.

In [ ]:
import numpy as np

# 1D indexing & slicing
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(f"arr[0]   = {arr[0]}")
print(f"arr[-1]  = {arr[-1]}")
print(f"arr[1:5] = {arr[1:5]}")
print(f"arr[::2] = {arr[::2]}")

# 2D indexing
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(f"\nMatrix:\n{mat}")
print(f"mat[0,0]  = {mat[0,0]}")
print(f"mat[1,2]  = {mat[1,2]}")
print(f"mat[-1,-1]= {mat[-1,-1]}")

# 2D slicing
print(f"\nFirst 2 rows: \n{mat[0:2]}")
print(f"Column 0: {mat[:, 0]}")
print(f"Sub-matrix [0:2, 1:3]:\n{mat[0:2, 1:3]}")
print(f"Last col: {mat[:, -1]}")

## Boolean Indexing (Filtering)

Applying a condition to an array creates a boolean mask (True/False array). Passing this mask back into the array extracts only the elements where the mask is True.

- **Step 1:** Apply condition → boolean array
- **Step 2:** Use boolean array as index → filtered result
- Combine conditions with `&` (and), `|` (or), `~` (not)
- `np.where(condition, x, y)` — conditional replacement

> Boolean indexing replaces loops for data filtering. In ML, you'll use it to select features, filter outliers, and mask missing values — all without writing a single `for`-loop.

In [ ]:
import numpy as np

mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Matrix:\n{mat}")

# Step 1: Create boolean mask
mask = mat % 2 == 0
print(f"\nEven mask:\n{mask}")

# Step 2: Apply mask to extract values
evens = mat[mask]
print(f"Even values: {evens}")

# One-liner (common pattern!)
print(f"Values > 5: {mat[mat > 5]}")

# Combine conditions (use & and |, not 'and')
result = mat[(mat > 2) & (mat < 8)]
print(f"2 < x < 8: {result}")

# np.where — conditional replacement
labels = np.where(mat > 5, "high", "low")
print(f"\nLabels:\n{labels}")

---
### Part 2 Exercises — Indexing, Slicing & Boolean Selection

**Exercise 2.1 — 2D Indexing & Slicing**

```python
mat = np.array([[ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12],
                [13, 14, 15, 16]])
```
Extract:  
(a) Element at row 2, col 3 (value = 12).  
(b) The entire third row.  
(c) The last column.  
(d) The 2×2 centre sub-matrix: rows 1–2, cols 1–2 (values 6, 7, 10, 11).  
(e) The matrix with its **rows reversed** using slicing.

In [ ]:
# Exercise 2.1
import numpy as np
mat = np.array([[ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12],
                [13, 14, 15, 16]])

# (a)

# (b)

# (c)

# (d)

# (e)

**Exercise 2.2 — Boolean indexing for filtering**

Given `temperatures = np.array([22, 35, 18, 40, 28, 15, 33, 26])`:  
(a) Extract all temperatures **above 30**.  
(b) Find the **indices** where temperature > 30.  
(c) **Count** how many days had temperature > 30.  
(d) **Clip** the array: replace any value below 20 with 20 — use boolean indexing, not `np.clip`.

In [ ]:
# Exercise 2.2
import numpy as np
temperatures = np.array([22, 35, 18, 40, 28, 15, 33, 26])

# (a)

# (b)

# (c)

# (d) work on a copy to preserve the original
temps_clipped = temperatures.copy()
# your clipping code here

**Exercise 2.3 — `np.where` for conditional logic**

Given `scores = np.array([45, 72, 88, 55, 91, 63, 78, 49])`:  
(a) Use `np.where` to label each score as `'pass'` (≥ 60) or `'fail'` (< 60).  
(b) Use `np.where` to add a 10-point bonus to any score < 60 and leave others unchanged.  
(c) After the bonus, how many students now pass?

In [ ]:
# Exercise 2.3
import numpy as np
scores = np.array([45, 72, 88, 55, 91, 63, 78, 49])

# (a)

# (b)

# (c)

**Exercise 2.4 — ML context: Flatten image data**

Images in ML are stored as `(N, H, W)` — N images, H rows, W columns.  

(a) Create 10 mock 8×8 grayscale images: `np.random.randint(0, 256, size=(10, 8, 8))`.  
(b) Reshape to a feature matrix of shape `(10, 64)` using `reshape(10, -1)`.  
(c) Print original and new shapes. Confirm total elements are unchanged.

In [ ]:
# Exercise 2.4
import numpy as np
np.random.seed(0)

# (a)

# (b)

# (c)

## Element-Wise Operations

Arithmetic operators (`+`, `-`, `*`, `/`, `**`) work element-wise on NumPy arrays — no loops needed. This is called **vectorisation**.

- Scalar + Array: `arr + 2` adds 2 to every element
- Array + Array: `a + b` adds element-by-element (same shape required)
- `*` is element-wise, **NOT** matrix multiply!
- For matrix multiplication use `np.dot(a, b)` or `a @ b`

> Vectorised code is not just cleaner — it's orders of magnitude faster. Never write `for i in range(len(arr))` when a NumPy operation exists.

In [ ]:
import numpy as np

a = np.array([[1, 0], [1, 2]])
print(f"a = \n{a}")

# Scalar operations
print(f"\na + 2 = \n{a + 2}")
print(f"a * 3 = \n{a * 3}")
print(f"a ** 2 = \n{a ** 2}")

# Array + Array (element-wise)
b = np.array([[0, 2], [1, 1]])
print(f"\nb = \n{b}")
print(f"a + b = \n{a + b}")
print(f"a * b = \n{a * b}")  # NOT matrix multiply!

# Matrix multiplication (dot product)
print(f"\na @ b (matrix multiply) =\n{a @ b}")
print(f"np.dot(a, b) =\n{np.dot(a, b)}")

## Aggregation & Statistics

NumPy provides fast aggregation functions: `sum`, `mean`, `std`, `min`, `max`, `argmin`, `argmax`.

The `axis` parameter controls the direction:
- `axis=None` — operate on ALL elements (default)
- `axis=0` — collapse rows → result per column
- `axis=1` — collapse columns → result per row
- `argmin`/`argmax` — index of min/max value

In [ ]:
import numpy as np

data = np.array([[10, 20, 30],
                 [40, 50, 60]])
print(f"Data:\n{data}\n")

# Global aggregation
print(f"Sum (all):  {np.sum(data)}")
print(f"Mean (all): {np.mean(data)}")
print(f"Std (all):  {np.std(data):.2f}")

# axis=0: collapse rows → per-column result
print(f"\nSum axis=0 (per col): {np.sum(data, axis=0)}")
print(f"Mean axis=0: {np.mean(data, axis=0)}")

# axis=1: collapse cols → per-row result
print(f"\nSum axis=1 (per row): {np.sum(data, axis=1)}")

# Min, Max, Argmax
print(f"\nMin: {np.min(data)}")
print(f"Max: {np.max(data)}")
print(f"Argmax (flat): {np.argmax(data)}")
print(f"Argmax axis=1: {np.argmax(data, axis=1)}")

## Matrix Multiplication (Dot Product)

Matrix multiplication uses `np.dot(a, b)` or the `@` operator. The rule: **(m×n) @ (n×p) = (m×p)**. The inner dimensions must match.

| Operation | Syntax | Description |
|-----------|--------|-------------|
| Element-wise | `a * b` | Multiply position by position |
| Matrix multiply | `a @ b` | Linear algebra dot product |
| Matrix multiply | `np.dot(a,b)` | Same as `@` |

> Matrix multiplication is at the heart of ML: neural network forward passes are just chains of matrix multiplications. Understanding shapes here prevents many bugs later.

In [ ]:
import numpy as np

# (1×2) @ (2×1) = (1×1) — dot product
a = np.array([1, 2])          # shape (2,)
b = np.array([[3], [4]])      # shape (2,1)
print(f"a shape: {a.shape}")
print(f"b shape: {b.shape}")
print(f"a @ b = {a @ b}")     # [11]

# (2×3) @ (3×2) = (2×2)
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,0],[0,1],[1,1]])
print(f"\nA (2x3):\n{A}")
print(f"B (3x2):\n{B}")
print(f"A @ B (2x2):\n{A @ B}")

# Compare: * vs @
C = np.array([[1,2],[3,4]])
D = np.array([[5,6],[7,8]])
print(f"\nC * D (element-wise):\n{C * D}")
print(f"C @ D (matrix mult):\n{C @ D}")

---
### Part 3 Exercises — Vectorisation, Aggregation & Linear Algebra

**Exercise 3.1 — Element-wise vs matrix multiplication**

Given `A = np.array([[1,2],[3,4]])` and `B = np.array([[5,6],[7,8]])`:  
(a) Compute the **element-wise product** `A * B`.  
(b) Compute the **matrix product** `A @ B`.  
(c) Are the results the same? Add a comment explaining why they differ.  
(d) Compute `A ** 2` (element-wise square) and `np.sqrt(A.astype(float))`.

In [ ]:
# Exercise 3.1
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# (a) element-wise product

# (b) matrix product

# (c) # They differ because * multiplies position-by-position, @ uses the dot-product rule

# (d)

**Exercise 3.2 — Aggregation with `axis`**

Exam scores for 4 students across 3 exams:
```python
scores = np.array([[85, 72, 90],
                   [78, 88, 65],
                   [92, 80, 76],
                   [60, 74, 88]])
```
(a) Compute the **mean score per student** (`axis=1`).  
(b) Compute the **mean score per exam** (`axis=0`).  
(c) Find the **index of the top student** with `np.argmax`.  
(d) **Standardise** the scores column-wise: subtract column mean, divide by column std.

In [ ]:
# Exercise 3.2
import numpy as np
scores = np.array([[85, 72, 90],
                   [78, 88, 65],
                   [92, 80, 76],
                   [60, 74, 88]])

# (a)

# (b)

# (c)

# (d)

**Exercise 3.3 — Shape rules for matrix multiplication**

(a) Create `A` with shape (4, 3) filled with ones, and `B` with shape (3, 5) filled with twos.  
(b) Compute `C = A @ B`. What shape is `C`? What is the value of each element?  
(c) Try `B @ A`. What error appears and why?  
(d) Fix it: compute `B.T @ A.T`. What shape do you get?

In [ ]:
# Exercise 3.3
import numpy as np

# (a)

# (b)

# (c) try B @ A
try:
    pass  # replace with B @ A
except ValueError as e:
    print('Error:', e)

# (d)

**Exercise 3.4 — Vectorised operations vs loops**

Given `arr = np.array([1.0, 4.0, 9.0, 16.0, 25.0])`:  
(a) Compute the square root of each element using `np.sqrt` (one line, no loop).  
(b) Compute the **cumulative sum** using `np.cumsum`.  
(c) Verify: `np.sum(arr)` should equal `np.cumsum(arr)[-1]`.

In [ ]:
# Exercise 3.4
import numpy as np
arr = np.array([1.0, 4.0, 9.0, 16.0, 25.0])

# (a)

# (b)

# (c)

**Exercise 3.5 — ML context: Linear layer forward pass**

A fully-connected layer computes `output = X @ W + b`:  
- `X`: input data, shape `(n_samples, n_features)`  
- `W`: weight matrix, shape `(n_features, n_outputs)`  
- `b`: bias vector, shape `(n_outputs,)`  

(a) Create `X` — 5 samples × 3 features, all ones.  
(b) Create `W` — shape `(3, 4)` using `np.random.randn(3, 4)` with seed 42.  
(c) Create `b` — shape `(4,)`, all zeros.  
(d) Compute the output. Print its shape — should be `(5, 4)`.

In [ ]:
# Exercise 3.5
import numpy as np
np.random.seed(42)

# (a)

# (b)

# (c)

# (d)  # output shape should be (5, 4)

## Stacking & Concatenation

Concatenation joins arrays along an **existing** axis. Stacking joins arrays along a **new** axis.

- `np.concatenate([a,b], axis=0)` — join along existing axis
- `np.vstack([a,b])` — stack vertically (add rows)
- `np.hstack([a,b])` — stack horizontally (add cols)
- `np.stack([a,b], axis=0)` — stack along NEW axis
- `np.array_split(arr, n)` — split into n parts

> In ML, you stack feature vectors into matrices, concatenate batches of data, and split datasets into train/test sets using these operations.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

# vstack — stack as rows
v = np.vstack([a, b, c])
print(f"vstack:\n{v}  shape={v.shape}")

# hstack — concatenate side by side
h = np.hstack([a, b, c])
print(f"\nhstack: {h}  shape={h.shape}")

# concatenate along axis=0 (same as vstack for 2D)
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6]])
cat = np.concatenate([m1, m2], axis=0)
print(f"\nConcat axis=0:\n{cat}")

# Splitting
arr = np.array([1, 2, 3, 4, 5, 6])
parts = np.array_split(arr, 3)
print(f"\nSplit into 3: {parts}")

## Iteration, Search & Sort

You can iterate arrays with `for` loops, but prefer vectorised operations when possible.

- `for x in arr:` — iterate over first axis
- `np.nditer(arr)` — iterate over all elements
- `np.where(condition)` — returns indices of True
- `np.sort(arr)` — sorted copy
- `np.argsort(arr)` — indices that would sort
- `np.unique(arr)` — unique values

> In practice, avoid explicit loops on NumPy arrays — they negate the speed advantage. Use boolean indexing and vectorised functions instead.

In [ ]:
import numpy as np

# Iteration (2D: iterates over rows)
mat = np.array([[1,2,3],[4,5,6]])
print("Iterating 2D (rows):")
for row in mat:
    print(f"  {row}")

# Iterate all elements
print("\nAll elements:", end=" ")
for x in np.nditer(mat):
    print(x, end=" ")

# Search with np.where
arr = np.array([1, 2, 3, 4, 5, 4, 4])
idx = np.where(arr == 4)
print(f"\n\nIndices where arr==4: {idx[0]}")

# Sort
print(f"Sorted: {np.sort(arr)}")
print(f"Argsort: {np.argsort(arr)}")

# Unique
print(f"Unique: {np.unique(arr)}")

---
### Part 4 Exercises — Stacking, Splitting, Iteration & Searching

**Exercise 4.1 — `vstack`, `hstack`, and `concatenate`**

Given `a=[1,2,3]`, `b=[4,5,6]`, `c=[7,8,9]`:  
(a) Stack them as rows using `np.vstack`. Print the shape.  
(b) Concatenate end-to-end using `np.hstack`. Print the shape.  
(c) Achieve (b) using `np.concatenate`.  
(d) Use `np.stack([a,b,c], axis=0)` and confirm the shape is `(3, 3)`.

In [ ]:
# Exercise 4.1
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

# (a)

# (b)

# (c)

# (d)

**Exercise 4.2 — Adding a bias column**

In linear regression a column of ones is added to the feature matrix for the intercept term.  

(a) Create `X = np.array([[2,3],[5,1],[8,4],[1,7]])` (4 samples × 2 features).  
(b) Create a `(4, 1)` column of ones.  
(c) Use `np.hstack` to attach the ones column to the **right** of `X`. Print the result.  
(d) What is the new shape? Why is the bias column useful?

In [ ]:
# Exercise 4.2
import numpy as np
X = np.array([[2, 3], [5, 1], [8, 4], [1, 7]])

# (b)

# (c)

# (d) shape is __ because ... the bias column allows the model to learn an intercept

**Exercise 4.3 — Splitting arrays**

(a) Create `arr = np.arange(0, 24)`. Split into **4 equal** parts using `np.array_split`.  
(b) Reshape `arr` to `(6, 4)`. Split into **3 equal** parts along `axis=0` (row-wise).  
(c) Print the shape of each part from (b).

In [ ]:
# Exercise 4.3
import numpy as np
arr = np.arange(0, 24)

# (a)

# (b)

# (c)

**Exercise 4.4 — Search, sort, and unique**

Given `arr = np.array([5, 2, 8, 1, 9, 3, 7, 4, 6, 3])`:  
(a) Return a **sorted** copy (leave the original unchanged).  
(b) Get the **indices** that would sort the array (`argsort`).  
(c) Use `np.where` to find indices where values are **greater than 5**.  
(d) Get the **unique values** and their **counts** using `np.unique(..., return_counts=True)`.

In [ ]:
# Exercise 4.4
import numpy as np
arr = np.array([5, 2, 8, 1, 9, 3, 7, 4, 6, 3])

# (a)

# (b)

# (c)

# (d)

**Exercise 4.5 — ML context: Shuffled train/test split**

(a) Create `indices = np.arange(100)` representing 100 sample IDs.  
(b) Set `np.random.seed(42)` and **shuffle** the indices in-place.  
(c) Slice: first 80 → train set, last 20 → test set.  
(d) Print the size of each set and the first 5 training indices.

In [ ]:
# Exercise 4.5
import numpy as np
np.random.seed(42)
indices = np.arange(100)

# (b)

# (c)

# (d)

## Random Number Generation

`numpy.random` provides functions for generating random numbers from various distributions. Use `np.random.seed()` for reproducibility — essential in ML experiments.

- `random.randint(low, high, size)` — random integers
- `random.rand(d0, d1)` — uniform [0, 1)
- `random.randn(d0, d1)` — standard normal
- `random.choice(arr, size)` — random sampling
- `random.shuffle(arr)` — shuffle in place
- `random.seed(42)` — fix the random state

> Always set a seed when running ML experiments. This makes your results reproducible — a requirement for scientific work and debugging.

In [ ]:
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Random integers
print("randint:", np.random.randint(0, 100, size=5))

# Uniform [0, 1)
print("rand:", np.random.rand(3).round(3))

# Standard normal (mean=0, std=1)
print("randn:", np.random.randn(5).round(3))

# Random choice from array
fruits = ["apple", "banana", "cherry"]
print("choice:", np.random.choice(fruits, size=4))

# 2D random matrix (3 rows x 4 cols)
mat = np.random.randint(1, 10, size=(3, 4))
print(f"\nRandom 3x4 matrix:\n{mat}")

# Reproducibility demo
np.random.seed(42)
a = np.random.rand(3)
np.random.seed(42)
b = np.random.rand(3)
print(f"\nSame seed -> same values: {np.array_equal(a, b)}")

## Broadcasting

Broadcasting allows NumPy to perform operations on arrays of different shapes. When shapes are incompatible in certain ways, NumPy automatically "stretches" the smaller array to match.

**Broadcasting rules:**
1. If arrays have different number of dimensions, prepend 1s to the smaller shape
2. Arrays with size 1 along a dimension are stretched to match the other
3. If shapes are incompatible in any dimension, an error is raised

> Broadcasting eliminates the need for explicit loops and temporary copies. In ML, it's how bias is added to every sample in a batch, or how normalisation is applied column-wise.

In [ ]:
import numpy as np

# Scalar broadcast: (2,3) + scalar
m = np.array([[1,2,3],[4,5,6]])
print(f"m + 10:\n{m + 10}\n")

# 1D broadcast: (2,3) + (3,) -> adds to each row
row = np.array([100, 200, 300])
print(f"m + [100,200,300]:\n{m + row}\n")

# Column broadcast: (2,3) + (2,1) -> adds to each col
col = np.array([[10], [20]])
print(f"m + [[10],[20]]:\n{m + col}\n")

# Practical ML example: normalise columns
data = np.array([[1.0, 200, 3000],
                 [4.0, 500, 6000],
                 [7.0, 800, 9000]])
col_mean = data.mean(axis=0)  # shape (3,)
col_std = data.std(axis=0)    # shape (3,)
normalised = (data - col_mean) / col_std
print(f"Normalised:\n{normalised.round(2)}")

---
### Part 5 Exercises — Random Number Generation & Broadcasting

**Exercise 5.1 — Seeds and reproducibility**

(a) Set `np.random.seed(7)`. Generate a 3×4 matrix of random integers from 1 to 20.  
(b) Generate **another** 3×4 matrix without resetting the seed. Is it the same?  
(c) Reset the seed to `7` and regenerate. Confirm it matches (a) using `np.array_equal`.

In [ ]:
# Exercise 5.1
import numpy as np

# (a)

# (b)

# (c)

**Exercise 5.2 — Normal distribution & the 68% rule**

(a) Generate 10,000 samples from a standard normal distribution (mean=0, std=1).  
(b) Print the sample **mean** and **standard deviation** — they should be close to 0 and 1.  
(c) Count how many values fall **within 1 std of the mean** (between −1 and 1).  
    What percentage? (The empirical rule predicts ≈68%.)

In [ ]:
# Exercise 5.2
import numpy as np
np.random.seed(0)

# (a)

# (b)

# (c)

**Exercise 5.3 — Simulation: dice rolls**

Simulate rolling a fair 6-sided die 10,000 times.  
(a) Generate rolls as integers from 1 to 6 inclusive.  
(b) Use `np.unique(..., return_counts=True)` to count each face.  
(c) Compute the mean roll — should be close to **3.5**.  
(d) What fraction of rolls were a **6**? Expected ≈ 1/6 ≈ 16.7%.

In [ ]:
# Exercise 5.3
import numpy as np
np.random.seed(42)

# (a)

# (b)

# (c)

# (d)

**Exercise 5.4 — Broadcasting: centre and scale**

Given:
```python
data = np.array([[10.0, 200.0, 3000.0],
                 [20.0, 400.0, 6000.0],
                 [30.0, 600.0, 9000.0]])
```
(a) Compute the **column mean** and **column std** (shape `(3,)`).  
(b) Subtract the column mean from `data` — confirm the result has zero column means.  
(c) Divide by column std — confirm each column now has std ≈ 1.  
(d) What broadcasting rule makes steps (b) and (c) work without loops?

In [ ]:
# Exercise 5.4
import numpy as np
data = np.array([[10.0,  200.0,  3000.0],
                 [20.0,  400.0,  6000.0],
                 [30.0,  600.0,  9000.0]])

# (a)

# (b)

# (c)

# (d) # Broadcasting works here because the shape (3,) is compatible with (3,3) ...

**Exercise 5.5 — ML context: Synthetic regression dataset**

Build a dataset for linear regression where the true relationship is **y = 3x + 2** with noise.  

(a) Set `np.random.seed(42)`. Generate 50 `X` values uniformly from [0, 10].  
(b) Generate noise `eps` ~ N(0, 1).  
(c) Compute `y = 3 * X + 2 + eps`.  
(d) Print the first 5 `(X, y)` pairs.  
(e) Compute the Pearson correlation: `np.corrcoef(X, y)[0, 1]`. Should be close to 1.

In [ ]:
# Exercise 5.5
import numpy as np
np.random.seed(42)

# (a)

# (b)

# (c)

# (d)

# (e)

## Summary & Next Steps

### Key NumPy Concepts Covered

| Topic | Key Functions |
|-------|---------------|
| Array creation | `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()` |
| Properties | `.ndim`, `.shape`, `.size`, `.dtype` |
| Reshaping | `.reshape()`, `.flatten()`, `.T` |
| Indexing | `arr[i,j]`, `arr[start:stop:step]`, boolean masks |
| Operations | `+`, `-`, `*`, `**`, `@`, `np.dot()` |
| Aggregation | `np.sum()`, `np.mean()`, `np.std()`, `axis=` param |
| Stacking | `np.vstack()`, `np.hstack()`, `np.concatenate()` |
| Search & Sort | `np.where()`, `np.sort()`, `np.argsort()` |
| Random | `np.random.seed()`, `randint()`, `rand()`, `randn()` |
| Broadcasting | Shape rules, column-wise normalisation |

> **Practice focus:** reshaping arrays, boolean indexing, and understanding `axis` behaviour in aggregation functions. These skills transfer directly to Pandas and ML model building.